version: '{build}'
image: Visual Studio 2015

environment:
  matrix:
    - COMPILER: MSVC
    - COMPILER: MSVC64
    - COMPILER: MinGW-w64
  BUILD_TYPE: MinSizeRel

install: 
  - git submodule update --init --recursive
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%PATH%

build_script:
  - mkdir out && cd out
  - if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_SH=CMAKE_SH-NOTFOUND ..
  - if [%COMPILER%]==[MSVC] cmake -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
  - if [%COMPILER%]==[MSVC64] cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
  - cmake --build . --parallel --config %BUILD_TYPE%

after_build:
  7z a tic80.zip %APPVEYOR_BUILD_FOLDER%\out\bin\tic80.exe

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/win
              
    curl --retry 3 --ftp-create-dirs -T tic80.zip %BUILDS_SERVER_PATH%/tic80-%COMPILER%.zip
